Repository midasit-dev/moaui, pull requests merged in 2023-08, with the labels that each got.

#1 Feature/initialize
  .gitignore
  .npmignore
  README.md
  craco.config.js
  dist/button/Styled.d.ts
  dist/button/Styled.js
  dist/button/index.d.ts
  dist/button/index.js
  dist/index.d.ts
  dist/index.js
  logo_circle.svg
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/index.css
  src/index.tsx
  src/lib/button/Styled.tsx
  src/lib/button/index.tsx
  src/lib/index.tsx
  src/logo.svg
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  tsconfig.json
  tsconfig.paths.json
Labels: good first issue

#3 children으로 svgIcon과 Text를 한번에 받을 수 있도록 Type 수정
  dist/button/Styled.d.ts
  dist/button/Styled.js
  dist/button/index.d.ts
  dist/button/index.js
  dist/index.d.ts
  dist/index.js
  package-lock.json
  package.json
  src/lib/IconButton/index.tsx
Labels: bug

#4 Feature/color
  src/lib/IconButton/Styled.tsx
  src/lib/button/Styled.tsx
  src/lib/color/index.ts
Labels: good first issue

#8 fix : dist 폴더가 없는 경우 npm i가 실행되지 않음
  package.json
  prepare.js
Labels: bug

#15 Feature/radio, radio group components 추가(디자인 반영안 개발)
  src/lib/Radio/Demo.tsx
  src/lib/Radio/Styled.tsx
  src/lib/Radio/index.test.tsx
  src/lib/Radio/index.tsx
  src/lib/RadioGroup/Demo.tsx
  src/lib/RadioGroup/Styled.tsx
  src/lib/RadioGroup/index.test.tsx
  src/lib/RadioGroup/index.tsx
Labels: enhancement

#11 Feature/text field
  src/lib/TextField/Styled.tsx
  src/lib/TextField/demo.tsx
  src/lib/TextField/index.test.tsx
  src/lib/TextField/index.tsx
  src/lib/index.ts
Labels: enhancement

#20 check, check group components 추가(디자인 반영안 개발)
  src/lib/Check/Demo.tsx
  src/lib/Check/Styled.tsx
  src/lib/Check/index.test.tsx
  src/lib/Check/index.tsx
  src/lib/CheckGroup/Demo.tsx
  src/lib/CheckGroup/Styled.tsx
  src/lib/CheckGroup/index.test.tsx
  src/lib/CheckGroup/index.tsx
  src/lib/index.ts
Labels: enhancement

#28 Feature/drop list
  src/lib/DropList/Styled.tsx
  src/lib/DropList/demo.tsx
  src/lib/DropList/index.tsx
  src/lib/index.ts
Labels: enhancement

#22 radio/radio group onChange 및 ariaLabel 관련 개선 진행
  src/lib/Radio/Demo.tsx
  src/lib/Radio/Styled.tsx
  src/lib/Radio/index.test.tsx
  src/lib/RadioGroup/Demo.tsx
  src/lib/RadioGroup/Styled.tsx
  src/lib/RadioGroup/index.test.tsx
  src/lib/RadioGroup/index.tsx
Labels: enhancement

#24 Feature/switch switch group components
  src/lib/Switch/Demo.tsx
  src/lib/Switch/Styled.tsx
  src/lib/Switch/index.test.tsx
  src/lib/Switch/index.tsx
  src/lib/SwitchGroup/Demo.tsx
  src/lib/SwitchGroup/Styled.tsx
  src/lib/SwitchGroup/index.test.tsx
  src/lib/SwitchGroup/index.tsx
  src/lib/Typography/index.test.tsx
  src/lib/index.ts
Labels: enhancement

#29 Feature/docs
  docs/.gitignore
  docs/README.md
  docs/craco.config.js
  docs/package-lock.json
  docs/package.json
  docs/public/favicon.ico
  docs/public/index.html
  docs/public/logo192.png
  docs/public/logo512.png
  docs/public/manifest.json
  docs/public/robots.txt
  docs/src/App.test.tsx
  docs/src/App.tsx
  docs/src/components/Typography.tsx
  docs/src/components/menu/Header.tsx
  docs/src/components/menu/Item.tsx
  docs/src/index.css
  docs/src/index.tsx
  docs/src/logo.svg
  docs/src/react-app-env.d.ts
  docs/src/reportWebVitals.ts
  docs/src/setupTests.ts
  docs/src/structure/Body.tsx
  docs/src/structure/Header.tsx
  docs/src/structure/ToggleButtons.tsx
  docs/src/svg/logo_circle_120.svg
  docs/src/svg/logo_circle_240.svg
  docs/src/svg/logo_circle_dark_40.svg
  docs/src/svg/logo_circle_light_40.svg
  docs/src/svg/moon_24.svg
  docs/src/svg/sun_24.svg
  docs/src/tailwindcss-input.css
  docs/src/tailwindcss-output.css
  docs/tailwind.config.js
  docs/tsconfig.json
  docs/tsconfig.paths.json
Labels: documentation

#33 Grid/Stack Wrapping component 추가
  src/lib/Grid/Demo.tsx
  src/lib/Grid/Styled.tsx
  src/lib/Grid/index.test.tsx
  src/lib/Grid/index.tsx
  src/lib/Stack/Demo.tsx
  src/lib/Stack/Styled.tsx
  src/lib/Stack/index.test.tsx
  src/lib/Stack/index.tsx
Labels: enhancement

#31 Feature/seperator
  src/lib/Seperator/Styled.tsx
  src/lib/Seperator/demo.tsx
  src/lib/Seperator/index.tsx
  src/lib/index.ts
Labels: enhancement

#37 Issue_#35 - TextField Props에 placeholder 추가
  src/lib/TextField/Styled.tsx
  src/lib/TextField/demo.tsx
  src/lib/TextField/index.tsx
Labels: enhancement

#36 Issue_#34 - TextField에 onChange 이벤트 추가
  src/lib/TextField/Styled.tsx
  src/lib/TextField/demo.tsx
  src/lib/TextField/index.tsx
Labels: bug

#38 Feature/drop list impove
  src/lib/DropList/Styled.tsx
  src/lib/DropList/demo.tsx
Labels: enhancement

#39 Feature/text field value
  src/lib/TextField/Styled.tsx
  src/lib/TextField/demo.tsx
Labels: enhancement

#41 TextField : Label Typography 적용되도록 수정, Width Property 추가
  src/lib/TextField/Styled.tsx
  src/lib/TextField/demo.tsx
  src/lib/TextField/index.tsx
Labels: enhancement

#43 Button Style Code 구조 변경
  src/lib/button/Demo.tsx
  src/lib/button/Styled.tsx
Labels: enhancement

#45 DropList의 하위 메뉴 width에 퍼센트 값 적용 오류 수정
  src/lib/DropList/Styled.tsx
  src/lib/DropList/demo.tsx
Labels: bug

#44 DataGrid 스타일 값 적용
  src/lib/DataGrid/Demo.tsx
  src/lib/DataGrid/Styled.tsx
Labels: enhancement

#47 Doc dev - TextField
  docs/src/components/menu/Item.tsx
  docs/src/components/menupages/ReferencePage.tsx
  docs/src/components/menupages/TextField.tsx
  docs/src/structure/Body.tsx
  docs/src/structure/Docs.tsx
Labels: documentation

#49 Doc Installation Page 제작
  docs/src/components/menupages/CodeBlock.tsx
  docs/src/components/menupages/Installation.tsx
  docs/src/components/menupages/ReferencePage.tsx
Labels: documentation

#46 Doc dev - Button
  docs/package.json
  docs/src/components/menu/Header.tsx
  docs/src/components/menu/Item.tsx
  docs/src/components/menupages/Button.tsx
  docs/src/components/menupages/Check.tsx
  docs/src/components/menupages/CodeBlock.tsx
  docs/src/components/menupages/Installation.tsx
  docs/src/components/menupages/ReferencePage.tsx
  docs/src/components/menupages/TextField.tsx
  docs/src/structure/Body.tsx
  docs/src/structure/Docs.tsx
  docs/src/structure/Header.tsx
  docs/src/tailwindcss-output.css
Labels: documentation

#52 Typography 관련 전역 설정 추가
  src/lib/DataGrid/Styled.tsx
  src/lib/MoaStyled/index.tsx
  src/lib/Radio/Styled.tsx
Labels: enhancement

#55 Switch Demo에 MoaSwtich Component 조작 UI 개발
  src/lib/Switch/Demo.tsx
  src/lib/Switch/Styled.tsx
  src/lib/SwitchGroup/Demo.tsx
Labels: documentation

#54 fixed : issue#42 text field remove warning
  src/lib/TextField/Styled.tsx
  src/lib/TextField/demo.tsx
  src/lib/TextField/index.tsx
Labels: bug

#57 Typography Demo에 Component 조작 UI 개발
  src/lib/Typography/Demo.tsx
  src/lib/Typography/Styled.tsx
Labels: documentation
